import type { Job } from "bullmq";
import {
  BillStatus,
  ChargeSourceType,
  ContractStatus,
  ExtraChargeStatus,
  Prisma,
} from "@prisma/client";

import { prisma } from "../prisma";

export type BillingJobData = {
  orgId: string;
  periodMonth: string;
};

function parsePeriodMonth(periodMonth: string) {
  const [yearValue, monthValue] = periodMonth.split("-");
  const year = Number(yearValue);
  const month = Number(monthValue);
  const startsOn = new Date(Date.UTC(year, month - 1, 1));
  const endsOn = new Date(Date.UTC(year, month, 0, 23, 59, 59, 999));
  return { startsOn, endsOn };
}

export async function handleBillingJob(job: Job<BillingJobData>) {
  const { orgId, periodMonth } = job.data;
  const { startsOn, endsOn } = parsePeriodMonth(periodMonth);

  const period = await prisma.billingPeriod.findUnique({
    where: { orgId_periodMonth: { orgId, periodMonth } },
  });

  if (period?.status === "CLOSED") {
    throw new Error(`Period ${periodMonth} is closed.`);
  }

  const contracts = await prisma.contract.findMany({
    where: {
      orgId,
      status: ContractStatus.ACTIVE,
      startDate: { lte: endsOn },
      OR: [{ endDate: null }, { endDate: { gte: startsOn } }],
    },
    include: { chargeItems: { where: { isActive: true } } },
  });

  let created = 0;
  let skipped = 0;

  for (const contract of contracts) {
    const existing = await prisma.bill.findUnique({
      where: {
        orgId_contractId_periodMonth: {
          orgId,
          contractId: contract.id,
          periodMonth,
        },
      },
    });

    if (existing) {
      skipped += 1;
      continue;
    }

    await prisma.$transaction(async (tx) => {
      const extras = await tx.extraCharge.findMany({
        where: {
          orgId,
          customerId: contract.customerId,
          periodMonth,
          status: ExtraChargeStatus.DRAFT,
          OR: [{ contractId: null }, { contractId: contract.id }],
        },
      });

      const contractItems = contract.chargeItems
        .filter(
          (item) =>
            (!item.startsAt || item.startsAt <= endsOn) &&
            (!item.endsAt || item.endsAt >= startsOn),
        )
        .map((item) => {
          const lineTotal = item.amount.mul(item.quantity).toDecimalPlaces(2);
          return {
            contractChargeItemId: item.id,
            sourceType: ChargeSourceType.CONTRACT,
            name: item.name,
            description: item.description,
            amount: item.amount,
            quantity: item.quantity,
            lineTotal,
          };
        });

      const extraItems = extras.map((extra) => ({
        extraChargeId: extra.id,
        sourceType: ChargeSourceType.EXTRA_CHARGE,
        name: extra.name,
        description: extra.description,
        amount: extra.amount,
        quantity: new Prisma.Decimal(1),
        lineTotal: extra.amount,
        occurredDate: extra.incurredDate,
      }));

      const items = [...contractItems, ...extraItems];
      const subtotal = items.reduce(
        (total, item) => total.plus(item.lineTotal),
        new Prisma.Decimal(0),
      );

      const bill = await tx.bill.create({
        data: {
          orgId,
          customerId: contract.customerId,
          contractId: contract.id,
          billNo: `BILL-${periodMonth}-${contract.code}`,
          periodMonth,
          subtotal,
          totalAmount: subtotal,
          items: { create: items },
          statusEvents: {
            create: {
              toStatus: BillStatus.DRAFT,
              note: "Generated by billing worker.",
            },
          },
        },
      });

      if (extras.length) {
        await tx.extraCharge.updateMany({
          where: { id: { in: extras.map((extra) => extra.id) } },
          data: { status: ExtraChargeStatus.BILLING_INCLUDED },
        });
      }

      await tx.outboxEvent.create({
        data: {
          orgId,
          topic: "bill.generated",
          aggregateType: "bill",
          aggregateId: bill.id,
          payload: { billId: bill.id, periodMonth },
        },
      });
    });

    created += 1;
  }

  return { orgId, periodMonth, created, skipped };
}
